START TRANSACTION;
CREATE TABLE "Departments" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "Name" text NOT NULL,
    "Budget" numeric NOT NULL,
    "StartDate" timestamp with time zone NOT NULL,
    "DepartmentHeadId" integer,
    CONSTRAINT "PK_Departments" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_Departments_Instructors_DepartmentHeadId" FOREIGN KEY ("DepartmentHeadId") REFERENCES "Instructors" ("Id")
);

CREATE INDEX "IX_Departments_DepartmentHeadId" ON "Departments" ("DepartmentHeadId");

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20250225111810_AddDepartmentRelation', '9.0.2');

COMMIT;

